### ISSUE TITLE
Music Bot error when requesting an invalid URL

### ISSUE THREAD

**Issue by Techtony96** [DiscordBolt/BoltBot#102]
![image](https://user-images.githubusercontent.com/1782682/32298018-6e39f632-bf27-11e7-915c-e4bc04171f4c.png)

```java
ERROR c.s.d.l.p.DefaultAudioPlayerManager - Error in loading item not_a_url
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:238)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:227)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.ajpappas.discord.api.commands.exceptions.CommandRuntimeException: Sorry, I was unable to find the song you specified.
	at net.ajpappas.discord.modules.audiostreamer.voice.VoiceManager$1.noMatches(VoiceManager.java:112)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:221)
	... 6 common frames omitted
```

**Comment by Techtony96** [comment]
Closing because of v3 rewrite
