### ISSUE TITLE
!Clip NPE

### ISSUE THREAD

**Issue by Techtony96** [DiscordBolt/BoltBot#117]
```
20:23:35.628 DEBUG s.b.d.Discord4J - Message from: Techtony96 (110926688455495680) in channel ID 201135773813047296: !clip shourd
20:23:35.924 ERROR c.d.a.c.CustomCommand - Uncaught exception during execution of "!clip" command.
20:23:35.925 ERROR c.d.a.c.CustomCommand - null
20:23:35.926 DEBUG c.d.a.c.CustomCommand - null
java.lang.NullPointerException: null
	at com.discordbolt.boltbot.system.twitch.objects.TwitchClipData.getViewURL(TwitchClipData.java:13)
	at com.discordbolt.boltbot.system.twitch.TwitchClip.generateClip(TwitchClip.java:38)
	at com.discordbolt.boltbot.modules.twitch.ClipCommand.clipCommand(ClipCommand.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.discordbolt.api.command.CustomCommand.preexec(CustomCommand.java:167)
	at com.discordbolt.api.command.CommandListener.onMesageEvent(CommandListener.java:43)
	at sx.blah.discord.api.events.EventDispatcher$MethodEventHandler.handle(EventDispatcher.java:680)
	at sx.blah.discord.api.events.EventDispatcher.lambda$null$17(EventDispatcher.java:610)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:23:35.980 DEBUG s.b.d.Discord4J - Message from: Bolt (194147128510119936) in channel ID 201135773813047296: An error has occurred while processing your command. Please try again later.
```

**Comment by Techtony96** [comment]
Closing because of v3 rewrite
