### ISSUE TITLE
Playlist Queuing Stacktrace

### ISSUE THREAD

**Issue by Techtony96** [DiscordBolt/BoltBot#73]
```
[ERROR] Error in loading item -pl
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:238)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:227)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: net.ajpappas.discord.api.commands.exceptions.CommandRuntimeException: Sorry, I was unable to find the song you specified.
        at net.ajpappas.discord.modules.audiostreamer.voice.VoiceManager$1.noMatches(VoiceManager.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:221)
        ... 6 common frames omitted```

**Comment by Techtony96** [comment]
This is caused by typing !play -pl with nothing else so it tries to look up the song with url "-pl"

The best fix for this would be to catch the exception instead of printing "your song is now being queued up"

**Comment by Techtony96** [comment]
Closing because of v3 rewrite
